# Generated by Django 5.2.5 on 2025-08-15 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoo',
            old_name='smo',
            new_name='srno',
        ),
    ]
